### ISSUE TITLE
How to setPointIntervalUnit, setLineColor and setFillColor on Series?

### ISSUE THREAD

**Issue by pblanchardie** [adessoAG/wicked-charts#53]
It looks like it's missing from the API. Are you interested by a PR?

**Comment by thombergs** [comment]
Hi,

yes, Highcharts has changed a lot since the last Wicked Charts release, so the API is probably a bit outdated.

A pull request is definitely welcome, I will merge it into the master branch. Don't know, when I'll be able to release the new version, though.

To fix the acute need: you can extend the Wicked Charts classes to support new attributes. See https://github.com/thombergs/wicked-charts/wiki/Feature:-Extending-Wicked-Charts.

**Comment by maximAtanasov** [comment]
I am closing this Pull-Request as it has been almost 3 years since the issue has been active and there has been no development.
